# Generated by Django 3.2.16 on 2022-12-21 20:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('left', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='left', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー（自分）')),
                ('right', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='right', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー（相手）')),
            ],
            options={
                'verbose_name': 'フレンド',
                'verbose_name_plural': 'フレンド',
                'db_table': 'friend',
            },
        ),
    ]
