# Generated by Django 3.2.16 on 2022-12-22 07:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('memore', '0002_auto_20221222_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='left',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='left', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー（自分）'),
        ),
        migrations.AlterField(
            model_name='friend',
            name='right',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='right', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー（相手）'),
        ),
    ]
