# Generated by Django 3.2.16 on 2022-12-22 09:04

import accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='userid',
            field=models.CharField(help_text='この項目は必須です。半角アルファベット、半角数字、アンダースコアで30文字以下にしてください。', max_length=30, primary_key=True, serialize=False, unique=True, validators=[accounts.validators.UnicodeUseridValidator()], verbose_name='ユーザーID'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(help_text='この項目は必須です。半角アルファベット、半角数字、@/./+/-/_ で30文字以下にしてください。', max_length=30, validators=[accounts.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
    ]
