# Generated by Django 3.2.16 on 2022-12-22 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20221222_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='icon',
            field=models.ImageField(default='images/default.jpg', upload_to='media/icon/', verbose_name='アイコン'),
        ),
    ]
