# Generated by Django 3.2.16 on 2022-12-22 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='icon',
            field=models.ImageField(default='icon/default.jpg', upload_to='icon', verbose_name='アイコン'),
        ),
    ]
